# Generated by Django 4.2.3 on 2023-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=48)),
                ('stumail', models.EmailField(max_length=48)),
                ('stupass', models.CharField(max_length=48)),
            ],
        ),
    ]
