# Generated by Django 4.2.3 on 2023-10-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=88)),
                ('field2', models.CharField(max_length=88)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent')),
                ('field3', models.CharField(max_length=88)),
                ('field4', models.CharField(max_length=88)),
            ],
            bases=('testapp.parent',),
        ),
        migrations.CreateModel(
            name='SubChild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.child')),
                ('field5', models.CharField(max_length=88)),
            ],
            bases=('testapp.child',),
        ),
    ]
